version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe
      MYSQL_USER: cafe
      MYSQL_PASSWORD: cafe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    image: minseokoh/servlet-tomcat
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: